CREATE TABLE IF NOT EXISTS roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS employees (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_number VARCHAR(50) UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE,
    employment_type VARCHAR(50),
    employment_status VARCHAR(50) NOT NULL DEFAULT 'Active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL UNIQUE REFERENCES employees(employee_id),
    role_id BIGINT NOT NULL REFERENCES roles(role_id),
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    account_status VARCHAR(50) NOT NULL DEFAULT 'Active',
    last_login TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attendance (
    attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    attendance_date DATE NOT NULL,
    check_in TIME,
    check_out TIME,
    hours_worked NUMERIC(6,2) NOT NULL DEFAULT 0 CHECK (hours_worked >= 0),
    status VARCHAR(50) NOT NULL DEFAULT 'Present',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (employee_id, attendance_date)
);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON attendance(attendance_date);

CREATE TABLE IF NOT EXISTS leave_types (
    leave_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    default_days INTEGER NOT NULL DEFAULT 0 CHECK (default_days >= 0),
    status VARCHAR(50) NOT NULL DEFAULT 'Active'
);

CREATE TABLE IF NOT EXISTS leave_balances (
    leave_balance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    leave_type_id BIGINT NOT NULL REFERENCES leave_types(leave_type_id),
    year SMALLINT NOT NULL CHECK (year BETWEEN 2000 AND 2200),
    total_days INTEGER NOT NULL DEFAULT 0 CHECK (total_days >= 0),
    used_days INTEGER NOT NULL DEFAULT 0 CHECK (used_days >= 0),
    remaining_days INTEGER NOT NULL DEFAULT 0 CHECK (remaining_days >= 0),
    UNIQUE (employee_id, leave_type_id, year)
);

CREATE TABLE IF NOT EXISTS leave_requests (
    leave_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    leave_type_id BIGINT NOT NULL REFERENCES leave_types(leave_type_id),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    number_of_days INTEGER NOT NULL CHECK (number_of_days > 0),
    reason TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    approved_by BIGINT REFERENCES users(user_id),
    approved_at TIMESTAMPTZ,
    rejection_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (end_date >= start_date)
);
CREATE INDEX IF NOT EXISTS idx_leave_requests_employee_status_dates
    ON leave_requests(employee_id, status, start_date, end_date);

CREATE TABLE IF NOT EXISTS employee_salaries (
    salary_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    basic_salary NUMERIC(12,2) NOT NULL CHECK (basic_salary >= 0),
    effective_from DATE NOT NULL,
    salary_status VARCHAR(50) NOT NULL DEFAULT 'Active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_salaries_employee_status_effective
    ON employee_salaries(employee_id, salary_status, effective_from);

CREATE TABLE IF NOT EXISTS payroll (
    payroll_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    pay_period_start DATE NOT NULL,
    pay_period_end DATE NOT NULL,
    basic_salary NUMERIC(12,2) NOT NULL CHECK (basic_salary >= 0),
    total_allowances NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (total_allowances >= 0),
    total_deductions NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (total_deductions >= 0),
    gross_salary NUMERIC(12,2) NOT NULL CHECK (gross_salary >= 0),
    net_salary NUMERIC(12,2) NOT NULL CHECK (net_salary >= 0),
    payroll_status VARCHAR(50) NOT NULL DEFAULT 'Draft',
    payment_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (pay_period_end >= pay_period_start)
);
CREATE INDEX IF NOT EXISTS idx_payroll_employee_period
    ON payroll(employee_id, pay_period_start, pay_period_end);

CREATE TABLE IF NOT EXISTS payroll_items (
    payroll_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_id BIGINT NOT NULL REFERENCES payroll(payroll_id) ON DELETE CASCADE,
    item_type VARCHAR(50) NOT NULL,
    item_name VARCHAR(255) NOT NULL,
    amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_payroll_items_payroll ON payroll_items(payroll_id);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS employees_set_updated_at ON employees;
CREATE TRIGGER employees_set_updated_at BEFORE UPDATE ON employees
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS users_set_updated_at ON users;
CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS attendance_set_updated_at ON attendance;
CREATE TRIGGER attendance_set_updated_at BEFORE UPDATE ON attendance
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS leave_requests_set_updated_at ON leave_requests;
CREATE TRIGGER leave_requests_set_updated_at BEFORE UPDATE ON leave_requests
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS payroll_set_updated_at ON payroll;
CREATE TRIGGER payroll_set_updated_at BEFORE UPDATE ON payroll
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO roles (role_name)
VALUES ('Admin'), ('HR'), ('Manager'), ('Employee')
ON CONFLICT (role_name) DO NOTHING;
