-- PostgreSQL expansion of Kamuti's MySQL backend delivery.
-- This migration is additive: it preserves all records created by 001_initial_schema.sql.

CREATE TABLE IF NOT EXISTS departments (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS positions (
    position_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_name VARCHAR(100) NOT NULL UNIQUE,
    department_id BIGINT NOT NULL REFERENCES departments(department_id),
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_positions_department ON positions(department_id);

ALTER TABLE roles
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE employees
    ADD COLUMN IF NOT EXISTS middle_name VARCHAR(100),
    ADD COLUMN IF NOT EXISTS gender VARCHAR(20),
    ADD COLUMN IF NOT EXISTS date_of_birth DATE,
    ADD COLUMN IF NOT EXISTS national_id VARCHAR(50),
    ADD COLUMN IF NOT EXISTS phone VARCHAR(30),
    ADD COLUMN IF NOT EXISTS address TEXT,
    ADD COLUMN IF NOT EXISTS department_id BIGINT REFERENCES departments(department_id),
    ADD COLUMN IF NOT EXISTS position_id BIGINT REFERENCES positions(position_id),
    ADD COLUMN IF NOT EXISTS hire_date DATE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_employees_national_id
    ON employees(national_id) WHERE national_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_employees_department ON employees(department_id);
CREATE INDEX IF NOT EXISTS idx_employees_position ON employees(position_id);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS auth_version INTEGER NOT NULL DEFAULT 1;

ALTER TABLE leave_types
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE leave_balances
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE employee_salaries
    ADD COLUMN IF NOT EXISTS effective_to DATE,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS manager_assignments (
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (manager_employee_id, employee_id),
    CHECK (manager_employee_id <> employee_id)
);
CREATE INDEX IF NOT EXISTS idx_manager_assignments_manager ON manager_assignments(manager_employee_id);
CREATE INDEX IF NOT EXISTS idx_manager_assignments_employee ON manager_assignments(employee_id);

CREATE TABLE IF NOT EXISTS benefits (
    benefit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    benefit_name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    benefit_type VARCHAR(30) NOT NULL CHECK (benefit_type IN ('Health', 'Insurance', 'Retirement', 'Allowance', 'Other')),
    provider VARCHAR(150),
    default_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (default_amount >= 0),
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employee_benefits (
    employee_benefit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    benefit_id BIGINT NOT NULL REFERENCES benefits(benefit_id),
    enrollment_date DATE NOT NULL,
    end_date DATE,
    amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (amount >= 0),
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive', 'Pending')),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (employee_id, benefit_id),
    CHECK (end_date IS NULL OR end_date >= enrollment_date)
);
CREATE INDEX IF NOT EXISTS idx_employee_benefits_benefit ON employee_benefits(benefit_id);

CREATE TABLE IF NOT EXISTS onboarding (
    onboarding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    start_date DATE NOT NULL,
    onboarding_status VARCHAR(30) NOT NULL DEFAULT 'Not Started'
        CHECK (onboarding_status IN ('Not Started', 'In Progress', 'Completed', 'On Hold')),
    assigned_hr_id BIGINT REFERENCES users(user_id),
    notes TEXT,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_onboarding_employee ON onboarding(employee_id);

CREATE TABLE IF NOT EXISTS onboarding_documents (
    document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    onboarding_id BIGINT NOT NULL REFERENCES onboarding(onboarding_id) ON DELETE CASCADE,
    document_name VARCHAR(150) NOT NULL,
    document_type VARCHAR(100),
    document_status VARCHAR(20) NOT NULL DEFAULT 'Pending'
        CHECK (document_status IN ('Pending', 'Submitted', 'Verified', 'Rejected')),
    document_path VARCHAR(500),
    rejection_reason TEXT,
    verified_by BIGINT REFERENCES users(user_id),
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_onboarding_documents_onboarding ON onboarding_documents(onboarding_id);

CREATE TABLE IF NOT EXISTS payroll_attendance (
    payroll_attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_id BIGINT NOT NULL REFERENCES payroll(payroll_id) ON DELETE CASCADE,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    working_days INTEGER NOT NULL DEFAULT 0 CHECK (working_days >= 0),
    days_present INTEGER NOT NULL DEFAULT 0 CHECK (days_present >= 0),
    days_absent INTEGER NOT NULL DEFAULT 0 CHECK (days_absent >= 0),
    days_on_leave INTEGER NOT NULL DEFAULT 0 CHECK (days_on_leave >= 0),
    days_late INTEGER NOT NULL DEFAULT 0 CHECK (days_late >= 0),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (payroll_id, employee_id)
);
CREATE INDEX IF NOT EXISTS idx_payroll_attendance_employee ON payroll_attendance(employee_id);

CREATE TABLE IF NOT EXISTS performance_cycles (
    cycle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_name VARCHAR(150) NOT NULL,
    description TEXT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft', 'Active', 'Closed', 'Archived')),
    created_by BIGINT NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (end_date >= start_date)
);
CREATE INDEX IF NOT EXISTS idx_performance_cycles_status ON performance_cycles(status);
CREATE INDEX IF NOT EXISTS idx_performance_cycles_dates ON performance_cycles(start_date, end_date);

CREATE TABLE IF NOT EXISTS performance_goals (
    goal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT NOT NULL REFERENCES performance_cycles(cycle_id),
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    goal_title VARCHAR(200) NOT NULL,
    goal_description TEXT,
    kpi VARCHAR(255),
    target_value VARCHAR(255),
    weight NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (weight BETWEEN 0 AND 100),
    progress NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100),
    status VARCHAR(20) NOT NULL DEFAULT 'Not Started'
        CHECK (status IN ('Not Started', 'In Progress', 'Completed', 'Cancelled')),
    due_date DATE,
    created_by BIGINT NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_performance_goals_cycle ON performance_goals(cycle_id);
CREATE INDEX IF NOT EXISTS idx_performance_goals_employee ON performance_goals(employee_id);
CREATE INDEX IF NOT EXISTS idx_performance_goals_status ON performance_goals(status);

CREATE TABLE IF NOT EXISTS performance_reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id BIGINT NOT NULL REFERENCES performance_cycles(cycle_id),
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    reviewer_employee_id BIGINT REFERENCES employees(employee_id) ON DELETE SET NULL,
    self_assessment TEXT,
    manager_comments TEXT,
    strengths TEXT,
    areas_for_improvement TEXT,
    development_plan TEXT,
    overall_rating NUMERIC(4,2) CHECK (overall_rating IS NULL OR overall_rating BETWEEN 0 AND 5),
    review_status VARCHAR(30) NOT NULL DEFAULT 'Not Started'
        CHECK (review_status IN ('Not Started', 'Self-Assessment', 'Manager Review', 'Finalized', 'Closed')),
    employee_submitted_at TIMESTAMPTZ,
    manager_submitted_at TIMESTAMPTZ,
    finalized_at TIMESTAMPTZ,
    finalized_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (cycle_id, employee_id)
);
CREATE INDEX IF NOT EXISTS idx_performance_reviews_employee ON performance_reviews(employee_id);
CREATE INDEX IF NOT EXISTS idx_performance_reviews_cycle ON performance_reviews(cycle_id);
CREATE INDEX IF NOT EXISTS idx_performance_reviews_status ON performance_reviews(review_status);

CREATE TABLE IF NOT EXISTS performance_goal_ratings (
    rating_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL REFERENCES performance_reviews(review_id) ON DELETE CASCADE,
    goal_id BIGINT NOT NULL REFERENCES performance_goals(goal_id),
    rating NUMERIC(4,2) CHECK (rating IS NULL OR rating BETWEEN 0 AND 5),
    comments TEXT,
    rated_by BIGINT NOT NULL REFERENCES employees(employee_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (review_id, goal_id)
);
CREATE INDEX IF NOT EXISTS idx_goal_ratings_review ON performance_goal_ratings(review_id);
CREATE INDEX IF NOT EXISTS idx_goal_ratings_goal ON performance_goal_ratings(goal_id);

CREATE TABLE IF NOT EXISTS performance_feedback (
    feedback_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL REFERENCES performance_reviews(review_id) ON DELETE CASCADE,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    feedback_by BIGINT NOT NULL REFERENCES users(user_id),
    feedback_type VARCHAR(20) NOT NULL CHECK (feedback_type IN ('Manager', 'Employee', 'HR')),
    feedback TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_performance_feedback_review ON performance_feedback(review_id);
CREATE INDEX IF NOT EXISTS idx_performance_feedback_employee ON performance_feedback(employee_id);

CREATE TABLE IF NOT EXISTS audit_logs (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id),
    action VARCHAR(100) NOT NULL,
    entity VARCHAR(80) NOT NULL,
    entity_id BIGINT,
    metadata TEXT,
    ip_address VARCHAR(45),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs(created_at);

CREATE TABLE IF NOT EXISTS notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    title VARCHAR(255) NOT NULL,
    entity VARCHAR(80) NOT NULL,
    entity_id BIGINT,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_notifications_owner ON notifications(user_id, read_at);

CREATE TABLE IF NOT EXISTS announcements (
    announcement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    body TEXT NOT NULL,
    audience VARCHAR(20) NOT NULL DEFAULT 'All'
        CHECK (audience IN ('All', 'Admin', 'HR', 'Manager', 'Employee')),
    expires_on DATE,
    created_by BIGINT NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS login_attempts (
    attempt_key CHAR(64) PRIMARY KEY,
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    window_started TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS job_vacancies (
    vacancy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    department_id BIGINT NOT NULL REFERENCES departments(department_id),
    position_id BIGINT NOT NULL REFERENCES positions(position_id),
    requirements TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Draft'
        CHECK (status IN ('Draft', 'Open', 'Closed', 'Filled', 'Cancelled')),
    closing_date DATE NOT NULL,
    manager_employee_id BIGINT REFERENCES employees(employee_id),
    created_by BIGINT NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_job_vacancies_status ON job_vacancies(status);

CREATE TABLE IF NOT EXISTS applicants (
    applicant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(30),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS job_applications (
    application_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacancy_id BIGINT NOT NULL REFERENCES job_vacancies(vacancy_id),
    applicant_id BIGINT NOT NULL REFERENCES applicants(applicant_id),
    cover_letter TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'Submitted'
        CHECK (status IN ('Submitted', 'Shortlisted', 'Interview', 'Offered', 'Hired', 'Rejected', 'Withdrawn')),
    decision_notes TEXT,
    hired_employee_id BIGINT REFERENCES employees(employee_id),
    created_by BIGINT NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (vacancy_id, applicant_id)
);
CREATE INDEX IF NOT EXISTS idx_job_applications_status ON job_applications(status);

CREATE TABLE IF NOT EXISTS interviews (
    interview_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES job_applications(application_id),
    interviewer_employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    scheduled_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Scheduled' CHECK (status IN ('Scheduled', 'Completed', 'Cancelled')),
    result VARCHAR(10) CHECK (result IS NULL OR result IN ('Pass', 'Fail', 'Hold')),
    notes TEXT,
    UNIQUE (application_id, interviewer_employee_id, scheduled_at)
);

CREATE TABLE IF NOT EXISTS training_courses (
    course_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    provider VARCHAR(150) NOT NULL,
    skills TEXT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    capacity INTEGER NOT NULL CHECK (capacity > 0),
    status VARCHAR(30) NOT NULL DEFAULT 'Planned'
        CHECK (status IN ('Planned', 'Open', 'In Progress', 'Completed', 'Cancelled')),
    created_by BIGINT NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS training_enrollments (
    enrollment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES training_courses(course_id),
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    status VARCHAR(20) NOT NULL DEFAULT 'Enrolled'
        CHECK (status IN ('Enrolled', 'In Progress', 'Completed', 'Cancelled')),
    completion_date DATE,
    score NUMERIC(5,2) CHECK (score IS NULL OR score BETWEEN 0 AND 100),
    development_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (course_id, employee_id)
);
CREATE INDEX IF NOT EXISTS idx_training_enrollments_employee ON training_enrollments(employee_id);

CREATE TABLE IF NOT EXISTS document_history (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES onboarding_documents(document_id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    reason TEXT,
    changed_by BIGINT NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS benefit_history (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_benefit_id BIGINT NOT NULL REFERENCES employee_benefits(employee_benefit_id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    amount NUMERIC(12,2) NOT NULL CHECK (amount >= 0),
    enrollment_date DATE NOT NULL,
    end_date DATE,
    changed_by BIGINT NOT NULL REFERENCES users(user_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS leave_types_set_updated_at ON leave_types;
CREATE TRIGGER leave_types_set_updated_at BEFORE UPDATE ON leave_types
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS leave_balances_set_updated_at ON leave_balances;
CREATE TRIGGER leave_balances_set_updated_at BEFORE UPDATE ON leave_balances
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS employee_salaries_set_updated_at ON employee_salaries;
CREATE TRIGGER employee_salaries_set_updated_at BEFORE UPDATE ON employee_salaries
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS manager_assignments_set_updated_at ON manager_assignments;
CREATE TRIGGER manager_assignments_set_updated_at BEFORE UPDATE ON manager_assignments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS benefits_set_updated_at ON benefits;
CREATE TRIGGER benefits_set_updated_at BEFORE UPDATE ON benefits
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS employee_benefits_set_updated_at ON employee_benefits;
CREATE TRIGGER employee_benefits_set_updated_at BEFORE UPDATE ON employee_benefits
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS onboarding_set_updated_at ON onboarding;
CREATE TRIGGER onboarding_set_updated_at BEFORE UPDATE ON onboarding
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS performance_cycles_set_updated_at ON performance_cycles;
CREATE TRIGGER performance_cycles_set_updated_at BEFORE UPDATE ON performance_cycles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS performance_goals_set_updated_at ON performance_goals;
CREATE TRIGGER performance_goals_set_updated_at BEFORE UPDATE ON performance_goals
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS performance_reviews_set_updated_at ON performance_reviews;
CREATE TRIGGER performance_reviews_set_updated_at BEFORE UPDATE ON performance_reviews
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS performance_goal_ratings_set_updated_at ON performance_goal_ratings;
CREATE TRIGGER performance_goal_ratings_set_updated_at BEFORE UPDATE ON performance_goal_ratings
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS job_applications_set_updated_at ON job_applications;
CREATE TRIGGER job_applications_set_updated_at BEFORE UPDATE ON job_applications
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
