-- Nicholas weekly delivery: reusable payroll information, working-hour policy,
-- and safe baseline reference data identified during all-role testing.
-- This migration is additive and does not delete or renumber existing records.

ALTER TABLE departments
    ADD COLUMN IF NOT EXISTS department_code VARCHAR(12);

CREATE UNIQUE INDEX IF NOT EXISTS uq_departments_code
    ON departments(department_code)
    WHERE department_code IS NOT NULL;

INSERT INTO departments (department_name, description, department_code)
VALUES ('General', 'Default holding department; replace with the organisation structure.', 'GEN')
ON CONFLICT (department_name) DO UPDATE
SET department_code = COALESCE(departments.department_code, EXCLUDED.department_code);

INSERT INTO positions (position_name, department_id, description)
SELECT 'General Staff', department_id, 'Default position; replace with the employee''s actual position.'
FROM departments
WHERE department_name = 'General'
ON CONFLICT (position_name) DO NOTHING;

UPDATE employees e
SET department_id = p.department_id
FROM positions p
WHERE e.department_id IS NULL
  AND e.position_id = p.position_id;

UPDATE employees
SET department_id = (SELECT department_id FROM departments WHERE department_name = 'General'),
    position_id = (
        SELECT p.position_id
        FROM positions p
        JOIN departments d ON d.department_id = p.department_id
        WHERE d.department_name = 'General'
        ORDER BY p.position_id
        LIMIT 1
    )
WHERE department_id IS NULL
  AND position_id IS NULL;

INSERT INTO positions (position_name, department_id, description)
SELECT d.department_name || ' Staff', d.department_id, 'Default position for this department.'
FROM departments d
WHERE NOT EXISTS (
    SELECT 1 FROM positions p WHERE p.department_id = d.department_id
)
ON CONFLICT (position_name) DO NOTHING;

UPDATE employees e
SET position_id = (
    SELECT p.position_id
    FROM positions p
    WHERE p.department_id = e.department_id
    ORDER BY p.position_id
    LIMIT 1
)
WHERE e.position_id IS NULL
  AND e.department_id IS NOT NULL;

-- Stable internal primary keys remain global. employee_number is the business-
-- facing identifier and can carry a department prefix without changing FKs.

CREATE TABLE IF NOT EXISTS work_policies (
    work_policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_name VARCHAR(120) NOT NULL UNIQUE,
    timezone VARCHAR(64) NOT NULL DEFAULT 'Africa/Lusaka',
    grace_minutes INTEGER NOT NULL DEFAULT 10 CHECK (grace_minutes BETWEEN 0 AND 180),
    early_departure_grace_minutes INTEGER NOT NULL DEFAULT 10
        CHECK (early_departure_grace_minutes BETWEEN 0 AND 180),
    minimum_half_day_hours NUMERIC(4,2) NOT NULL DEFAULT 4
        CHECK (minimum_half_day_hours BETWEEN 0 AND 24),
    status VARCHAR(20) NOT NULL DEFAULT 'Active'
        CHECK (status IN ('Active', 'Inactive')),
    created_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_work_policies_single_active
    ON work_policies(status)
    WHERE status = 'Active';

CREATE TABLE IF NOT EXISTS work_policy_days (
    work_policy_day_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_policy_id BIGINT NOT NULL REFERENCES work_policies(work_policy_id) ON DELETE CASCADE,
    day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
    is_working_day BOOLEAN NOT NULL DEFAULT TRUE,
    start_time TIME,
    end_time TIME,
    expected_hours NUMERIC(4,2) NOT NULL DEFAULT 0 CHECK (expected_hours BETWEEN 0 AND 24),
    UNIQUE (work_policy_id, day_of_week),
    CHECK (
        (is_working_day = FALSE AND start_time IS NULL AND end_time IS NULL AND expected_hours = 0)
        OR
        (is_working_day = TRUE AND start_time IS NOT NULL AND end_time IS NOT NULL
            AND end_time > start_time AND expected_hours > 0)
    )
);

INSERT INTO work_policies (
    policy_name,
    timezone,
    grace_minutes,
    early_departure_grace_minutes,
    minimum_half_day_hours,
    status
)
VALUES ('Default Work Schedule', 'Africa/Lusaka', 10, 10, 4, 'Active')
ON CONFLICT (policy_name) DO NOTHING;

INSERT INTO work_policy_days (
    work_policy_id,
    day_of_week,
    is_working_day,
    start_time,
    end_time,
    expected_hours
)
SELECT wp.work_policy_id, schedule.day_of_week, schedule.is_working_day,
       schedule.start_time, schedule.end_time, schedule.expected_hours
FROM work_policies wp
CROSS JOIN (
    VALUES
        (0, FALSE, NULL::TIME, NULL::TIME, 0::NUMERIC),
        (1, TRUE,  '08:00'::TIME, '17:00'::TIME, 8::NUMERIC),
        (2, TRUE,  '08:00'::TIME, '17:00'::TIME, 8::NUMERIC),
        (3, TRUE,  '08:00'::TIME, '17:00'::TIME, 8::NUMERIC),
        (4, TRUE,  '08:00'::TIME, '17:00'::TIME, 8::NUMERIC),
        (5, TRUE,  '08:00'::TIME, '17:00'::TIME, 8::NUMERIC),
        (6, FALSE, NULL::TIME, NULL::TIME, 0::NUMERIC)
) AS schedule(day_of_week, is_working_day, start_time, end_time, expected_hours)
WHERE wp.policy_name = 'Default Work Schedule'
ON CONFLICT (work_policy_id, day_of_week) DO NOTHING;

ALTER TABLE employees
    ADD COLUMN IF NOT EXISTS work_policy_id BIGINT REFERENCES work_policies(work_policy_id);

UPDATE employees
SET work_policy_id = (
    SELECT work_policy_id FROM work_policies WHERE status = 'Active' LIMIT 1
)
WHERE work_policy_id IS NULL;

ALTER TABLE attendance
    ADD COLUMN IF NOT EXISTS scheduled_start TIME,
    ADD COLUMN IF NOT EXISTS scheduled_end TIME,
    ADD COLUMN IF NOT EXISTS expected_hours NUMERIC(4,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS late_minutes INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS early_departure_minutes INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS attendance_source VARCHAR(30) NOT NULL DEFAULT 'Manual',
    ADD COLUMN IF NOT EXISTS verification_status VARCHAR(30) NOT NULL DEFAULT 'Unverified';

CREATE INDEX IF NOT EXISTS idx_attendance_employee_period
    ON attendance(employee_id, attendance_date);

CREATE TABLE IF NOT EXISTS payroll_components (
    payroll_component_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component_name VARCHAR(120) NOT NULL UNIQUE,
    component_type VARCHAR(20) NOT NULL CHECK (component_type IN ('Allowance', 'Deduction')),
    calculation_type VARCHAR(20) NOT NULL DEFAULT 'Fixed'
        CHECK (calculation_type IN ('Fixed', 'Percentage')),
    default_value NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (default_value >= 0),
    taxable BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employee_payroll_components (
    employee_payroll_component_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    payroll_component_id BIGINT NOT NULL REFERENCES payroll_components(payroll_component_id),
    component_value NUMERIC(12,2) NOT NULL CHECK (component_value >= 0),
    effective_from DATE NOT NULL,
    effective_to DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    created_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (effective_to IS NULL OR effective_to >= effective_from),
    UNIQUE (employee_id, payroll_component_id, effective_from)
);

CREATE INDEX IF NOT EXISTS idx_employee_payroll_components_active
    ON employee_payroll_components(employee_id, status, effective_from, effective_to);

INSERT INTO payroll_components (
    component_name,
    component_type,
    calculation_type,
    default_value,
    taxable,
    description
)
VALUES
    ('Transport Allowance', 'Allowance', 'Fixed', 0, FALSE, 'Organisation-defined transport support.'),
    ('Housing Allowance', 'Allowance', 'Fixed', 0, FALSE, 'Organisation-defined housing support.'),
    ('Overtime', 'Allowance', 'Fixed', 0, TRUE, 'Approved overtime payment; no automatic legal rate is assumed.'),
    ('Pension Contribution', 'Deduction', 'Fixed', 0, FALSE, 'Organisation-defined pension contribution.'),
    ('Other Deduction', 'Deduction', 'Fixed', 0, FALSE, 'Approved non-statutory deduction.')
ON CONFLICT (component_name) DO NOTHING;

ALTER TABLE employee_salaries
    ADD COLUMN IF NOT EXISTS currency CHAR(3) NOT NULL DEFAULT 'ZMW';

ALTER TABLE payroll
    ADD COLUMN IF NOT EXISTS currency CHAR(3) NOT NULL DEFAULT 'ZMW',
    ADD COLUMN IF NOT EXISTS created_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS processed_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS processed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS payment_reference VARCHAR(120);

ALTER TABLE payroll_attendance
    ADD COLUMN IF NOT EXISTS expected_hours NUMERIC(8,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS hours_worked NUMERIC(8,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS overtime_hours NUMERIC(8,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS shortfall_hours NUMERIC(8,2) NOT NULL DEFAULT 0;

-- Baseline names fix the empty leave-type selector. Entitlements remain zero
-- until Admin/HR applies the organisation's approved leave policy.
INSERT INTO leave_types (leave_name, description, default_days, status)
VALUES
    ('Annual Leave', 'Planned paid leave; entitlement must be configured by the organisation.', 0, 'Active'),
    ('Sick Leave', 'Health-related absence; entitlement must be configured by the organisation.', 0, 'Active'),
    ('Compassionate Leave', 'Approved compassionate absence.', 0, 'Active'),
    ('Unpaid Leave', 'Approved leave without salary entitlement.', 0, 'Active')
ON CONFLICT (leave_name) DO NOTHING;

DROP TRIGGER IF EXISTS work_policies_set_updated_at ON work_policies;
CREATE TRIGGER work_policies_set_updated_at BEFORE UPDATE ON work_policies
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS payroll_components_set_updated_at ON payroll_components;
CREATE TRIGGER payroll_components_set_updated_at BEFORE UPDATE ON payroll_components
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS employee_payroll_components_set_updated_at ON employee_payroll_components;
CREATE TRIGGER employee_payroll_components_set_updated_at BEFORE UPDATE ON employee_payroll_components
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
