-- Testing-review fixes: attendance schedule, onboarding requests/forms and
-- progress tracking. Additive and idempotent; nothing is dropped or renumbered.

-- 1. Attendance schedule. Check-ins up to 09:15 are on time (09:00 start plus a
--    15 minute grace period). Friday, Saturday and Sunday are half-day schedules,
--    which the attendance module reports as 'Present (Half Day)' / 'Late (Half Day)'.
UPDATE work_policies
SET grace_minutes = 15
WHERE policy_name = 'Default Work Schedule';

UPDATE work_policy_days wpd
SET is_working_day = TRUE,
    start_time = '09:00'::TIME,
    end_time = CASE WHEN wpd.day_of_week IN (5, 6, 0) THEN '13:00'::TIME ELSE '17:00'::TIME END,
    expected_hours = CASE WHEN wpd.day_of_week IN (5, 6, 0) THEN 4 ELSE 8 END
FROM work_policies wp
WHERE wp.work_policy_id = wpd.work_policy_id
  AND wp.policy_name = 'Default Work Schedule';

-- 2. Onboarding: every active employee without an onboarding record gets one,
--    plus the standard document requests, so "Choose a request" has options.
INSERT INTO onboarding (employee_id, start_date, onboarding_status, assigned_hr_id)
SELECT e.employee_id,
       COALESCE(e.hire_date, CURRENT_DATE),
       'Not Started',
       (SELECT u.user_id
        FROM users u
        JOIN roles r ON r.role_id = u.role_id
        WHERE r.role_name IN ('Admin', 'HR') AND u.account_status = 'Active'
        ORDER BY (r.role_name = 'HR') DESC, u.user_id
        LIMIT 1)
FROM employees e
WHERE e.employment_status = 'Active'
  AND NOT EXISTS (SELECT 1 FROM onboarding o WHERE o.employee_id = e.employee_id);

INSERT INTO onboarding_documents (onboarding_id, document_name, document_type)
SELECT o.onboarding_id, d.document_name, d.document_type
FROM onboarding o
CROSS JOIN (VALUES
    ('National ID / NRC copy', 'Identification'),
    ('Proof of address', 'Identification'),
    ('Bank account details', 'Financial'),
    ('Academic certificates', 'Qualification')
) AS d(document_name, document_type)
WHERE o.onboarding_status <> 'Completed'
  AND NOT EXISTS (
      SELECT 1 FROM onboarding_documents od
      WHERE od.onboarding_id = o.onboarding_id AND od.document_name = d.document_name
  );

-- 3. Onboarding information form: the employee submits key data, then HR, Admin
--    or the employee's assigned Manager approves or rejects it.
CREATE TABLE IF NOT EXISTS onboarding_forms (
    form_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    onboarding_id BIGINT NOT NULL UNIQUE REFERENCES onboarding(onboarding_id) ON DELETE CASCADE,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    form_data JSONB NOT NULL DEFAULT '{}'::JSONB,
    status VARCHAR(20) NOT NULL DEFAULT 'Pending'
        CHECK (status IN ('Pending', 'Submitted', 'Approved', 'Rejected')),
    submitted_at TIMESTAMPTZ,
    reviewed_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    reviewed_at TIMESTAMPTZ,
    rejection_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_onboarding_forms_employee_status
    ON onboarding_forms(employee_id, status);

DROP TRIGGER IF EXISTS onboarding_forms_set_updated_at ON onboarding_forms;
CREATE TRIGGER onboarding_forms_set_updated_at BEFORE UPDATE ON onboarding_forms
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 4. Progress tracker: HR/Managers define records with milestones and tick them
--    off; employees see their own progress.
CREATE TABLE IF NOT EXISTS progress_records (
    record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    title VARCHAR(150) NOT NULL,
    description TEXT,
    due_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'In Progress'
        CHECK (status IN ('In Progress', 'Completed', 'Cancelled')),
    created_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_progress_records_employee ON progress_records(employee_id, status);

CREATE TABLE IF NOT EXISTS progress_milestones (
    milestone_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id BIGINT NOT NULL REFERENCES progress_records(record_id) ON DELETE CASCADE,
    title VARCHAR(150) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_complete BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMPTZ,
    completed_by BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_progress_milestones_record ON progress_milestones(record_id, sort_order);

DROP TRIGGER IF EXISTS progress_records_set_updated_at ON progress_records;
CREATE TRIGGER progress_records_set_updated_at BEFORE UPDATE ON progress_records
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
