-- Nicholas weekly delivery: explicit demonstration leave limits and
-- position-based salary guidelines. These figures are editable examples for
-- the project demonstration; they are not statutory or production advice.

ALTER TABLE leave_types
    ADD COLUMN IF NOT EXISTS max_requests_per_year SMALLINT,
    ADD COLUMN IF NOT EXISTS max_consecutive_days SMALLINT,
    ADD COLUMN IF NOT EXISTS policy_notes TEXT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'leave_types_max_requests_per_year_check'
          AND conrelid = 'leave_types'::regclass
    ) THEN
        ALTER TABLE leave_types
            ADD CONSTRAINT leave_types_max_requests_per_year_check
            CHECK (max_requests_per_year IS NULL OR max_requests_per_year BETWEEN 1 AND 52);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'leave_types_max_consecutive_days_check'
          AND conrelid = 'leave_types'::regclass
    ) THEN
        ALTER TABLE leave_types
            ADD CONSTRAINT leave_types_max_consecutive_days_check
            CHECK (max_consecutive_days IS NULL OR max_consecutive_days BETWEEN 1 AND 366);
    END IF;
END $$;

-- Insert missing demonstration leave types without replacing organisation data.
INSERT INTO leave_types (leave_name, description, default_days, status)
VALUES
    ('Annual Leave', 'Planned paid leave.', 24, 'Active'),
    ('Sick Leave', 'Health-related absence.', 14, 'Active'),
    ('Compassionate Leave', 'Approved compassionate absence.', 5, 'Active'),
    ('Maternity Leave', 'Maternity absence.', 90, 'Active'),
    ('Paternity Leave', 'Paternity absence.', 7, 'Active'),
    ('Study Leave', 'Approved study or examination leave.', 10, 'Active'),
    ('Unpaid Leave', 'Approved leave without salary.', 30, 'Active')
ON CONFLICT (leave_name) DO NOTHING;

-- Existing non-zero entitlements remain untouched. The request-frequency and
-- consecutive-day fields are new policy values and can be changed later.
UPDATE leave_types lt
SET default_days = CASE WHEN lt.default_days = 0 THEN policy.recommended_days ELSE lt.default_days END,
    max_requests_per_year = policy.max_requests,
    max_consecutive_days = policy.max_consecutive,
    policy_notes = policy.notes
FROM (VALUES
    ('Annual Leave', 24, 3, 10, 'Demonstration policy: split the annual allowance across no more than three requests.'),
    ('Sick Leave', 14, 6, 7, 'Demonstration policy: supporting documentation may be requested for longer absences.'),
    ('Compassionate Leave', 5, 2, 5, 'Demonstration policy: intended for qualifying family or emergency circumstances.'),
    ('Maternity Leave', 90, 1, 90, 'Demonstration value only; confirm current employment law and organisation policy.'),
    ('Paternity Leave', 7, 1, 7, 'Demonstration value only; confirm current employment law and organisation policy.'),
    ('Study Leave', 10, 2, 5, 'Demonstration policy: intended for approved study or examination periods.'),
    ('Unpaid Leave', 30, 2, 15, 'Demonstration policy: requires HR approval after paid leave options are considered.')
) AS policy(leave_name, recommended_days, max_requests, max_consecutive, notes)
WHERE lt.leave_name = policy.leave_name;

CREATE INDEX IF NOT EXISTS idx_leave_requests_employee_type_year_active
    ON leave_requests(employee_id, leave_type_id, start_date)
    WHERE status IN ('Pending', 'Approved');

CREATE TABLE IF NOT EXISTS position_salary_guidelines (
    salary_guideline_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_id BIGINT NOT NULL REFERENCES positions(position_id) ON DELETE CASCADE,
    recommended_basic_salary NUMERIC(12,2) NOT NULL CHECK (recommended_basic_salary > 0),
    currency CHAR(3) NOT NULL DEFAULT 'ZMW',
    effective_from DATE NOT NULL,
    effective_to DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (position_id, effective_from),
    CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

CREATE INDEX IF NOT EXISTS idx_position_salary_guidelines_position
    ON position_salary_guidelines(position_id, status, effective_from, effective_to);

CREATE UNIQUE INDEX IF NOT EXISTS uq_position_salary_guidelines_current
    ON position_salary_guidelines(position_id)
    WHERE status = 'Active' AND effective_to IS NULL;

INSERT INTO position_salary_guidelines (
    position_id,
    recommended_basic_salary,
    currency,
    effective_from,
    notes
)
SELECT p.position_id, policy.monthly_salary, 'ZMW', DATE '2026-10-01',
       'Demonstration monthly basic-salary guideline; HR must approve the employee salary record.'
FROM (VALUES
    ('HR Manager', 18500.00::NUMERIC),
    ('HR Officer', 11500.00::NUMERIC),
    ('Finance Manager', 21000.00::NUMERIC),
    ('Accountant', 13500.00::NUMERIC),
    ('IT Manager', 23000.00::NUMERIC),
    ('Software Developer', 16500.00::NUMERIC),
    ('Systems Administrator', 14500.00::NUMERIC),
    ('Operations Manager', 19000.00::NUMERIC),
    ('Operations Officer', 10500.00::NUMERIC),
    ('Sales Manager', 18000.00::NUMERIC),
    ('Sales Executive', 10000.00::NUMERIC),
    ('General Staff', 7500.00::NUMERIC),
    ('Human Resources Staff', 9500.00::NUMERIC),
    ('Finance Staff', 10500.00::NUMERIC),
    ('Information Technology Staff', 12500.00::NUMERIC),
    ('Operations Staff', 9000.00::NUMERIC),
    ('Sales & Marketing Staff', 8500.00::NUMERIC)
) AS policy(position_name, monthly_salary)
JOIN positions p ON p.position_name = policy.position_name
ON CONFLICT (position_id, effective_from) DO UPDATE
SET recommended_basic_salary = EXCLUDED.recommended_basic_salary,
    currency = EXCLUDED.currency,
    notes = EXCLUDED.notes,
    status = 'Active',
    effective_to = NULL;

DROP TRIGGER IF EXISTS position_salary_guidelines_set_updated_at ON position_salary_guidelines;
CREATE TRIGGER position_salary_guidelines_set_updated_at
BEFORE UPDATE ON position_salary_guidelines
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
